apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bu4fe1d97-dotnet-basic
  janus-idp.io/tekton: bu4fe1d97-dotnet-basic
  backstage.io/kubernetes-id: bu4fe1d97-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bu4fe1d97-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
